import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.css';
import styles from './globals.css';
import classNames from 'classnames/bind';
import Header from '@/components/header/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const cx = classNames.bind(styles);
export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <head>
                <link
                    rel='icon'
                    href='/icon?<generated>'
                    type='image/<generated>'
                    sizes='<generated>'
                />
            </head>
            <body className={cx('wrapper')}>
                <Header />
                {children}
            </body>
        </html>
    );
}
